### ISSUE TITLE
Missed documentation for configuration of Redis servers

### ISSUE THREAD

**Issue by binlab** [renzholy/sider#54]
Interesting to try your **Redis** Dashboard, but a missed documentation on how to do it. From the source code it became clear that need to configure the environment variable `REDIS_OPTS` like **JSON** in the next format
```json
[
    {
        "Addrs": "redis0:6379"
    },
    {
        "Addrs": "redis1:6379"
    }
]
```
But it doesn't seem to work, could you clarify what is wrong or update the documentation? 
Thank you very much!

**Comment by renzholy** [comment]
sorry for replying too late.

https://github.com/renzholy/sider/commit/2a060f7c64cdabc3702e7d83f19e8c1579c32636
